### ISSUE TITLE
urlpatterns warnings in 1.8

### ISSUE THREAD

**Issue by zfdang** [Mischback/django-project-skeleton#1]
urls.py:9: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^admin/', include(admin.site.urls)),

**Comment by Mischback** [comment]
Should be resolved by fixing https://github.com/Mischback/django-project-skeleton/issues/2

I'll give it a try with the upcoming Django 1.11-version, but won't put up a simple 1.8 fix.

**Comment by Mischback** [comment]
This should be covered in 1.2
